app_name: microsite

fullnameOverride: microsite

replicas: 6
# build info not used atm
build:
  enabled: false
  build_tag: latest
  source_docker_file_path: Dockerfile
  # source_context_dir: "/"
  # source_ref: master
  # source_repo: https://github.com/springdo/microsite.git
# Docker deets
image_repository: image-registry.openshift-image-registry.svc:5000
image_name: microsite
image_namespace: residency

# likely over written by the Argo definition
image_version: latest
a_b_deploy:
  weight: 100
  # svc_name:
fathom: false
# OCP route
route: true
# custom end point injected by config map. This is likely to changed
config_map: '{}'
